language: go

go:
- "1.10"

git:
  depth: 3


go_import_path: github.com/kubernetes-sigs/kubebuilder

# Install must be set to prevent default `go get` to run.
# The dependencies have already been vendored by `dep` so
# we don't need to fetch them.
install:
  -

script:
  ./test.sh

# TBD. Suppressing for now.
notifications:
  email: false
